/**
 * Curated static list of Indian Railways trains.
 * Source: Indian Railways official timetable (IRCTC / NTES public data).
 * Used for autocomplete — no external dependency needed.
 */
export interface TrainEntry {
  number: string;
  name: string;
}

export const TRAINS: TrainEntry[] = [
  // Rajdhani Express
  { number: "12301", name: "Howrah Rajdhani Express" },
  { number: "12302", name: "New Delhi Rajdhani Express" },
  { number: "12305", name: "Howrah Rajdhani Express" },
  { number: "12306", name: "New Delhi Rajdhani Express" },
  { number: "12309", name: "Rajendra Nagar Rajdhani Express" },
  { number: "12310", name: "New Delhi Rajdhani Express" },
  { number: "12311", name: "Kalka Mail" },
  { number: "12313", name: "Sealdah Rajdhani Express" },
  { number: "12314", name: "New Delhi Rajdhani Express" },
  { number: "12423", name: "Dibrugarh Rajdhani Express" },
  { number: "12424", name: "Dibrugarh Rajdhani Express" },
  { number: "12431", name: "Thiruvananthapuram Rajdhani Express" },
  { number: "12432", name: "Hazrat Nizamuddin Rajdhani Express" },
  { number: "12433", name: "Hazrat Nizamuddin Chennai Rajdhani" },
  { number: "12434", name: "Chennai Rajdhani Express" },
  { number: "12439", name: "Ranchi Rajdhani Express" },
  { number: "12440", name: "New Delhi Rajdhani Express" },
  { number: "12441", name: "Bilaspur Rajdhani Express" },
  { number: "12442", name: "New Delhi Rajdhani Express" },
  { number: "12453", name: "Ranchi Rajdhani Express" },
  { number: "12454", name: "Hazrat Nizamuddin Rajdhani Express" },
  // Shatabdi Express
  { number: "12001", name: "Bhopal Shatabdi Express" },
  { number: "12002", name: "New Delhi Shatabdi Express" },
  { number: "12003", name: "Lucknow Swaran Shatabdi Express" },
  { number: "12004", name: "New Delhi Shatabdi Express" },
  { number: "12005", name: "Kalka Shatabdi Express" },
  { number: "12006", name: "New Delhi Shatabdi Express" },
  { number: "12011", name: "Kalka Shatabdi Express" },
  { number: "12012", name: "New Delhi Shatabdi Express" },
  { number: "12013", name: "Amritsar Shatabdi Express" },
  { number: "12014", name: "New Delhi Shatabdi Express" },
  { number: "12015", name: "Ajmer Shatabdi Express" },
  { number: "12016", name: "New Delhi Shatabdi Express" },
  { number: "12017", name: "Dehradun Shatabdi Express" },
  { number: "12018", name: "New Delhi Shatabdi Express" },
  { number: "12019", name: "Howrah Shatabdi Express" },
  { number: "12020", name: "Ranchi Shatabdi Express" },
  { number: "12021", name: "Howrah Shatabdi Express" },
  { number: "12022", name: "New Delhi Shatabdi Express" },
  { number: "12023", name: "Pune Shatabdi Express" },
  { number: "12024", name: "Mumbai CST Shatabdi Express" },
  { number: "12025", name: "Pune Shatabdi Express" },
  { number: "12026", name: "Secunderabad Shatabdi Express" },
  { number: "12027", name: "Mumbai CSMT Shatabdi Express" },
  { number: "12028", name: "Chennai Shatabdi Express" },
  { number: "12029", name: "Amritsar Swarna Shatabdi Express" },
  { number: "12030", name: "New Delhi Shatabdi Express" },
  // Vande Bharat Express
  { number: "22401", name: "New Delhi Vande Bharat Express" },
  { number: "22402", name: "New Delhi Vande Bharat Express" },
  { number: "20901", name: "Mumbai Central Vande Bharat Express" },
  { number: "20902", name: "Gandhinagar Vande Bharat Express" },
  { number: "22435", name: "New Delhi Vande Bharat Express" },
  { number: "22436", name: "Varanasi Vande Bharat Express" },
  { number: "22437", name: "New Delhi Vande Bharat Express" },
  { number: "22438", name: "Mata Vaishno Devi Katra Vande Bharat" },
  { number: "20901", name: "Mumbai Central Vande Bharat" },
  { number: "22549", name: "Secunderabad Vande Bharat Express" },
  { number: "22550", name: "Visakhapatnam Vande Bharat Express" },
  { number: "20613", name: "Howrah Vande Bharat Express" },
  { number: "20614", name: "New Jalpaiguri Vande Bharat Express" },
  { number: "22221", name: "CSMT Mumbai Rajdhani Express" },
  { number: "22222", name: "Hazrat Nizamuddin Rajdhani Express" },
  // Duronto Express
  { number: "12213", name: "Mumbai LTT Duronto Express" },
  { number: "12214", name: "New Delhi Duronto Express" },
  { number: "12219", name: "Mumbai CSMT Duronto Express" },
  { number: "12220", name: "Secunderabad Duronto Express" },
  { number: "12223", name: "Mumbai CSMT Duronto Express" },
  { number: "12224", name: "Lokmanya Tilak Duronto Express" },
  { number: "12245", name: "Howrah Duronto Express" },
  { number: "12246", name: "Yesvantpur Duronto Express" },
  { number: "12269", name: "Chennai Duronto Express" },
  { number: "12270", name: "Hazrat Nizamuddin Duronto Express" },
  { number: "12283", name: "Ernakulam Duronto Express" },
  { number: "12284", name: "Hazrat Nizamuddin Duronto Express" },
  { number: "12285", name: "Secunderabad Duronto Express" },
  { number: "12286", name: "Hazrat Nizamuddin Duronto Express" },
  // Garib Rath
  { number: "12203", name: "Saharsa Garib Rath Express" },
  { number: "12204", name: "Amritsar Garib Rath Express" },
  { number: "12207", name: "Jammu Tawi Garib Rath Express" },
  { number: "12208", name: "Mumbai LTT Garib Rath Express" },
  { number: "12209", name: "Mumbai LTT Garib Rath Express" },
  { number: "12210", name: "Patna Garib Rath Express" },
  { number: "12211", name: "Mumbai LTT Garib Rath Express" },
  { number: "12212", name: "Gorakhpur Garib Rath Express" },
  // Jan Shatabdi
  { number: "12051", name: "Dadar Jan Shatabdi Express" },
  { number: "12052", name: "Madgaon Jan Shatabdi Express" },
  { number: "12053", name: "Haridwar Jan Shatabdi Express" },
  { number: "12054", name: "New Delhi Jan Shatabdi Express" },
  { number: "12055", name: "Dehradun Jan Shatabdi Express" },
  { number: "12056", name: "New Delhi Jan Shatabdi Express" },
  { number: "12057", name: "Una Himachal Jan Shatabdi Express" },
  { number: "12058", name: "New Delhi Jan Shatabdi Express" },
  { number: "12059", name: "Kota Jan Shatabdi Express" },
  { number: "12060", name: "New Delhi Jan Shatabdi Express" },
  // Superfast Express
  { number: "12101", name: "Jnaneswari Super Deluxe Express" },
  { number: "12102", name: "Mumbai CST Jnaneswari Super Deluxe" },
  { number: "12115", name: "Siddheshwar Express" },
  { number: "12116", name: "Siddheshwar Express" },
  { number: "12123", name: "Deccan Queen Express" },
  { number: "12124", name: "Deccan Queen Express" },
  { number: "12125", name: "Pragati Express" },
  { number: "12126", name: "Pragati Express" },
  { number: "12127", name: "Intercity Express" },
  { number: "12128", name: "Intercity Express" },
  { number: "12129", name: "Azad Hind Express" },
  { number: "12130", name: "Azad Hind Express" },
  { number: "12131", name: "Pune Express" },
  { number: "12132", name: "Mumbai CST Express" },
  { number: "12133", name: "Mangala Lakshadweep Express" },
  { number: "12134", name: "Mangala Lakshadweep Express" },
  { number: "12137", name: "Punjab Mail" },
  { number: "12138", name: "Punjab Mail" },
  { number: "12141", name: "Patliputra Express" },
  { number: "12142", name: "Patliputra Express" },
  { number: "12143", name: "LTT Express" },
  { number: "12144", name: "Solapur Express" },
  // Famous Mail/Express
  { number: "12151", name: "Samarsata Express" },
  { number: "12152", name: "Samarsata Express" },
  { number: "12153", name: "Habibganj Express" },
  { number: "12154", name: "Habibganj Express" },
  { number: "12155", name: "Shridham Express" },
  { number: "12156", name: "Shridham Express" },
  { number: "12157", name: "Sabarmati Express" },
  { number: "12158", name: "Sabarmati Express" },
  { number: "12159", name: "Jaipur Express" },
  { number: "12160", name: "Mumbai Jaipur Express" },
  // Delhi area
  { number: "12201", name: "Mumbai LTT Garib Rath Express" },
  { number: "12202", name: "New Delhi Garib Rath Express" },
  { number: "12229", name: "Lucknow Mail" },
  { number: "12230", name: "Lucknow Mail" },
  { number: "12237", name: "Begampura Express" },
  { number: "12238", name: "Begampura Express" },
  { number: "12241", name: "Chalukya Express" },
  { number: "12242", name: "Chalukya Express" },
  { number: "12243", name: "Coimbatore Shatabdi Express" },
  { number: "12244", name: "Coimbatore Shatabdi Express" },
  { number: "12247", name: "Yuva Express" },
  { number: "12248", name: "Yuva Express" },
  { number: "12251", name: "Wainganga Express" },
  { number: "12252", name: "Wainganga Express" },
  { number: "12253", name: "Anga Express" },
  { number: "12254", name: "Anga Express" },
  { number: "12255", name: "Yoga Express" },
  { number: "12256", name: "Yoga Express" },
  { number: "12257", name: "Kashi Vishwanath Express" },
  { number: "12258", name: "Kashi Vishwanath Express" },
  { number: "12259", name: "Sealdah Duronto Express" },
  { number: "12260", name: "New Delhi Duronto Express" },
  // Intercity / Major Trains
  { number: "22943", name: "Indore Intercity SF Express" },
  { number: "22944", name: "Daund Intercity SF Express" },
  { number: "12901", name: "Gujarat Mail" },
  { number: "12902", name: "Gujarat Mail" },
  { number: "12903", name: "Golden Temple Mail" },
  { number: "12904", name: "Golden Temple Mail" },
  { number: "12909", name: "Bandra T Garib Rath Express" },
  { number: "12910", name: "Bandra T Garib Rath Express" },
  { number: "12919", name: "Malwa Express" },
  { number: "12920", name: "Malwa Express" },
  { number: "12925", name: "Paschim Express" },
  { number: "12926", name: "Paschim Express" },
  { number: "12927", name: "Karnavati Express" },
  { number: "12928", name: "Karnavati Express" },
  { number: "12929", name: "Dadar Paschim Express" },
  { number: "12930", name: "Dadar Paschim Express" },
  { number: "12931", name: "Mumbai Double Decker Express" },
  { number: "12932", name: "Ahmedabad Double Decker Express" },
  { number: "12933", name: "Karnavati Express" },
  { number: "12934", name: "Karnavati Express" },
  { number: "12941", name: "Parasnath Express" },
  { number: "12942", name: "Parasnath Express" },
  { number: "12943", name: "Udyan Abha Toofan Express" },
  { number: "12944", name: "Udyan Abha Toofan Express" },
  { number: "12947", name: "Azimabad Express" },
  { number: "12948", name: "Azimabad Express" },
  { number: "12951", name: "Mumbai Rajdhani Express" },
  { number: "12952", name: "New Delhi Rajdhani Express" },
  { number: "12953", name: "August Kranti Rajdhani Express" },
  { number: "12954", name: "August Kranti Rajdhani Express" },
  { number: "12957", name: "Swarna Jayanti Rajdhani Express" },
  { number: "12958", name: "New Delhi Rajdhani Express" },
  { number: "12961", name: "Avantika Express" },
  { number: "12962", name: "Avantika Express" },
  { number: "12963", name: "Mewar Express" },
  { number: "12964", name: "Mewar Express" },
  { number: "12965", name: "Garbha Express" },
  { number: "12966", name: "Garbha Express" },
  { number: "12967", name: "Jaipur Express" },
  { number: "12968", name: "Jaipur Express" },
  { number: "12969", name: "Cbe Jaipur Express" },
  { number: "12970", name: "Jaipur Cbe Express" },
  { number: "12971", name: "Bandra T Bhavnagar Express" },
  { number: "12972", name: "Bhavnagar Bandra T Express" },
  { number: "12975", name: "Mysore Jaipur Express" },
  { number: "12976", name: "Jaipur Mysore Express" },
  // Tamil Nadu / South
  { number: "12601", name: "Chennai Mail" },
  { number: "12602", name: "Chennai Mail" },
  { number: "12603", name: "Hyderabad Express" },
  { number: "12604", name: "Hyderabad Chennai Express" },
  { number: "12605", name: "Pallavan Express" },
  { number: "12606", name: "Pallavan Express" },
  { number: "12607", name: "Lalbagh Express" },
  { number: "12608", name: "Lalbagh Express" },
  { number: "12609", name: "Chennai Intercity Express" },
  { number: "12610", name: "Chennai Intercity Express" },
  { number: "12611", name: "Chennai Nellai Express" },
  { number: "12612", name: "Chennai Nellai Express" },
  { number: "12621", name: "Tamil Nadu Express" },
  { number: "12622", name: "Tamil Nadu Express" },
  { number: "12623", name: "Nellai Express" },
  { number: "12624", name: "Nellai Express" },
  { number: "12625", name: "Kerala Express" },
  { number: "12626", name: "Kerala Express" },
  { number: "12627", name: "Karnataka Express" },
  { number: "12628", name: "Karnataka Express" },
  { number: "12629", name: "Malabar Express" },
  { number: "12630", name: "Malabar Express" },
  { number: "12631", name: "Nellai Superfast Express" },
  { number: "12632", name: "Nellai Superfast Express" },
  { number: "12633", name: "Kanyakumari Express" },
  { number: "12634", name: "Kanyakumari Express" },
  { number: "12639", name: "Brindavan Express" },
  { number: "12640", name: "Brindavan Express" },
  { number: "12641", name: "Thirukkural Express" },
  { number: "12642", name: "Thirukkural Express" },
  { number: "12643", name: "Nagercoil Express" },
  { number: "12644", name: "Nagercoil Express" },
  { number: "12649", name: "Karnataka Sampark Kranti Express" },
  { number: "12650", name: "Karnataka Sampark Kranti Express" },
  { number: "12651", name: "Millenium Express" },
  { number: "12652", name: "Millenium Express" },
  { number: "12657", name: "Bengaluru Mail" },
  { number: "12658", name: "Chennai Mail" },
  { number: "12659", name: "Gurudev Express" },
  { number: "12660", name: "Gurudev Express" },
  { number: "12671", name: "Nilagiri Express" },
  { number: "12672", name: "Nilagiri Express" },
  { number: "12673", name: "Cheran Express" },
  { number: "12674", name: "Cheran Express" },
  { number: "12675", name: "Kovai Express" },
  { number: "12676", name: "Kovai Express" },
  { number: "12677", name: "Ernakulam Express" },
  { number: "12678", name: "Ernakulam Express" },
  { number: "12679", name: "Chennai Express" },
  { number: "12680", name: "Coimbatore Express" },
  { number: "12681", name: "Coimbatore Express" },
  { number: "12682", name: "Chennai Express" },
  // North India
  { number: "12311", name: "Netaji Express" },
  { number: "12312", name: "Kalka Mail" },
  { number: "12315", name: "Annanya Express" },
  { number: "12316", name: "Annanya Express" },
  { number: "12317", name: "Akal Takht Express" },
  { number: "12318", name: "Akal Takht Express" },
  { number: "12321", name: "Howrah Mumbai Mail" },
  { number: "12322", name: "Mumbai CST Howrah Mail" },
  { number: "12323", name: "Vibhuti Express" },
  { number: "12324", name: "Vibhuti Express" },
  { number: "12325", name: "Koaa Nagercoil Express" },
  { number: "12326", name: "Koaa Nagercoil Express" },
  { number: "12327", name: "Upasana Express" },
  { number: "12328", name: "Upasana Express" },
  { number: "12329", name: "West Bengal Sampark Kranti Express" },
  { number: "12330", name: "West Bengal Sampark Kranti Express" },
  { number: "12331", name: "Himgiri Express" },
  { number: "12332", name: "Himgiri Express" },
  { number: "12333", name: "Vibhuti Express" },
  { number: "12334", name: "Vibhuti Express" },
  { number: "12335", name: "Bhagalpur Express" },
  { number: "12336", name: "Bhagalpur Express" },
  { number: "12337", name: "Shantiniketan Express" },
  { number: "12338", name: "Shantiniketan Express" },
  { number: "12339", name: "Coalfield Express" },
  { number: "12340", name: "Coalfield Express" },
  { number: "12341", name: "Agnibina Express" },
  { number: "12342", name: "Agnibina Express" },
  { number: "12343", name: "Darjeeling Mail" },
  { number: "12344", name: "Darjeeling Mail" },
  { number: "12345", name: "Saraighat Express" },
  { number: "12346", name: "Saraighat Express" },
  { number: "12347", name: "Rourkela Express" },
  { number: "12348", name: "Rourkela Express" },
  { number: "12349", name: "BSB Express" },
  { number: "12350", name: "BSB Express" },
  { number: "12351", name: "Danapur Express" },
  { number: "12352", name: "Patna Rajdhani Express" },
  { number: "12353", name: "LTT Howrah Express" },
  { number: "12354", name: "Howrah LTT Express" },
  { number: "12355", name: "Archana Express" },
  { number: "12356", name: "Archana Express" },
  { number: "12357", name: "Durgiana Express" },
  { number: "12358", name: "Durgiana Express" },
  { number: "12359", name: "Kolkata Patna Express" },
  { number: "12360", name: "Kolkata Express" },
  // East Coast Railway
  { number: "12801", name: "Purushottam Express" },
  { number: "12802", name: "Purushottam Express" },
  { number: "12803", name: "Swarna Jayanti Express" },
  { number: "12804", name: "Swarna Jayanti Express" },
  { number: "12805", name: "Janmabhoomi Express" },
  { number: "12806", name: "Janmabhoomi Express" },
  { number: "12807", name: "Samta Express" },
  { number: "12808", name: "Samta Express" },
  { number: "12809", name: "Mumbai Howrah Mail" },
  { number: "12810", name: "Howrah Mumbai Mail" },
  { number: "12811", name: "LTT Hatia Express" },
  { number: "12812", name: "Hatia LTT Express" },
  { number: "12813", name: "Steel Express" },
  { number: "12814", name: "Steel Express" },
  { number: "12815", name: "Nandan Kanan Express" },
  { number: "12816", name: "Nandan Kanan Express" },
  { number: "12817", name: "Jharkhand Sampark Kranti Express" },
  { number: "12818", name: "Jharkhand Sampark Kranti Express" },
  { number: "12819", name: "Odisha Sampark Kranti Express" },
  { number: "12820", name: "Odisha Sampark Kranti Express" },
  { number: "12821", name: "Dhauli Express" },
  { number: "12822", name: "Dhauli Express" },
  { number: "12823", name: "Chennai Puri Express" },
  { number: "12824", name: "Puri Chennai Express" },
  { number: "12825", name: "Chhattisgarh Express" },
  { number: "12826", name: "Chhattisgarh Express" },
  { number: "12827", name: "Howrah Intercity Express" },
  { number: "12828", name: "Howrah Intercity Express" },
  { number: "12829", name: "Bhubaneswar Rajdhani Express" },
  { number: "12830", name: "New Delhi Rajdhani Express" },
  // Sampark Kranti
  { number: "12449", name: "Goa Sampark Kranti Express" },
  { number: "12450", name: "Hazrat Nizamuddin Sampark Kranti" },
  { number: "12451", name: "Shram Shakti Express" },
  { number: "12452", name: "Shram Shakti Express" },
  { number: "12455", name: "Delhi Sarai Rohilla Hissar Express" },
  { number: "12456", name: "Hissar Delhi Sarai Rohilla Express" },
  { number: "12457", name: "New Delhi Chandigarh Express" },
  { number: "12458", name: "Chandigarh New Delhi Express" },
  { number: "12459", name: "New Delhi Amritsar Express" },
  { number: "12460", name: "Amritsar New Delhi Express" },
  { number: "12461", name: "Mandor Express" },
  { number: "12462", name: "Mandor Express" },
  { number: "12463", name: "Jodhpur Express" },
  { number: "12464", name: "Jodhpur Express" },
  // Kolkata Rajdhani
  { number: "12381", name: "Poorva Express" },
  { number: "12382", name: "Poorva Express" },
  { number: "12391", name: "Shramjeevi Express" },
  { number: "12392", name: "Shramjeevi Express" },
  { number: "12393", name: "Sampoorna Kranti Express" },
  { number: "12394", name: "Sampoorna Kranti Express" },
  { number: "12395", name: "Ziyarat Express" },
  { number: "12396", name: "Ziyarat Express" },
  { number: "12397", name: "Mahabodhi Express" },
  { number: "12398", name: "Mahabodhi Express" },
  { number: "12399", name: "Bandra T Terminus Rajasthan Express" },
  { number: "12400", name: "Rajasthan Express" },
  { number: "12401", name: "Nanda Devi Express" },
  { number: "12402", name: "Nanda Devi Express" },
  { number: "12403", name: "Allahabad Express" },
  { number: "12404", name: "Jhansi Express" },
  { number: "12405", name: "Gondwana Express" },
  { number: "12406", name: "Gondwana Express" },
  { number: "12407", name: "Koraput Express" },
  { number: "12408", name: "Koraput Express" },
  { number: "12409", name: "Gondwana Express" },
  { number: "12410", name: "Gondwana Express" },
  { number: "12411", name: "Bhrigu Express" },
  { number: "12412", name: "Bhrigu Express" },
  { number: "12413", name: "Ajmer Express" },
  { number: "12414", name: "Ajmer Express" },
  { number: "12415", name: "Indore Express" },
  { number: "12416", name: "Indore Express" },
  { number: "12417", name: "Prayagraj Express" },
  { number: "12418", name: "Prayagraj Express" },
  { number: "12419", name: "Gomti Express" },
  { number: "12420", name: "Gomti Express" },
  { number: "12421", name: "Pataliputra Express" },
  { number: "12422", name: "Pataliputra Express" },
];

/**
 * Search trains by number prefix or name substring (case-insensitive, max 10 results).
 */
export function searchTrains(query: string, limit = 10): TrainEntry[] {
  const q = query.trim().toLowerCase();
  if (!q || q.length < 2) return [];

  const results: TrainEntry[] = [];
  const seen = new Set<string>();

  for (const t of TRAINS) {
    if (seen.has(t.number)) continue;
    const matchesNumber = t.number.startsWith(q);
    const matchesName = t.name.toLowerCase().includes(q);
    if (matchesNumber || matchesName) {
      results.push(t);
      seen.add(t.number);
      if (results.length >= limit) break;
    }
  }

  return results;
}
